# Generated by Django 5.2.7 on 2025-10-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('id_hokhau', models.AutoField(primary_key=True, serialize=False)),
                ('so_can_ho', models.CharField(max_length=20)),
                ('dien_tich', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id_vaitro', models.AutoField(primary_key=True, serialize=False)),
                ('ten_vaitro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id_nhankhau', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('cccd', models.CharField(blank=True, max_length=12, null=True)),
                ('quan_he_chu_ho', models.CharField(blank=True, max_length=50, null=True)),
                ('ho_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_khau', to='core.hokhau')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id_taikhoan', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('vaitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tai_khoan', to='core.vaitro')),
            ],
        ),
    ]
