# Generated by Django 5.2.7 on 2025-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('id_ho_khau', models.AutoField(primary_key=True, serialize=False)),
                ('so_can_ho', models.CharField(max_length=50)),
                ('dien_tich', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id_nhan_khau', models.AutoField(primary_key=True, serialize=False)),
                ('id_ho_khau', models.CharField()),
                ('ngay_sinh', models.DateField()),
                ('can_cuoc_cong_dan', models.CharField(max_length=12, unique=True)),
                ('quan_he_chu_ho', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id_tai_khoan', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('vai_tro', models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='serviceusage',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='serviceusage',
            name='service',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceUsage',
        ),
    ]
