# Generated by Django 5.2.7 on 2025-10-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hokhau',
            table='hokhau',
        ),
        migrations.AlterModelTable(
            name='nhankhau',
            table='nhankhau',
        ),
        migrations.AlterModelTable(
            name='taikhoan',
            table='taikhoan',
        ),
        migrations.AlterModelTable(
            name='vaitro',
            table='vaitro',
        ),
    ]
